### ISSUE TITLE
Split payload fails downstream with Null 

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud-stream-app-starters/splitter#1]
As a user, I'm trying to use the `splitter-processor` in the following stream; however, upon consuming the split payload downstream I see the attached errors.

**streams (1):**
```
stream create foo --definition "http --port=8086 | split-JSON: splitter --expression=#jsonPath(payload,'$.station.readings') --outputType=application/x-spring-tuple | log"
stream create bar --definition ":foo.split-JSON > field-value-counter --name=salsa --fieldName=stationid --inputType=application/x-spring-tuple"
```

**streams (2):**
```
stream create foo --definition "http --port=8086 | split-JSON: splitter --expression=#jsonPath(payload,'$.station.readings') --spring.cloud.stream.bindings.output.contentType='application/json' | log"
stream create bar --definition ":foo.split-JSON > field-value-counter --name=salsa --fieldName=stationid --spring.cloud.stream.bindings.input.contentType='application/json'"
```

**error:**
```
Caused by: java.lang.
IllegalArgumentException: payload must not be null
```
---

**streams (3):**
```
stream create foo --definition "http --port=8086 | split-JSON: splitter --expression=#jsonPath(payload,'$.station.readings') | log"
stream create bar --definition ":foo.split-JSON > field-value-counter --fieldName=payload.stationid --name=StationId"
```

This stream doesn't do anything; no errors either.

---

**post:**
```
http post --target http://localhost:8086 --data {"station":{"readings":[{"stationid":100,"customerid":200,"timestamp":"2017-07-15T08:09:10"},{"stationid":101,"customerid":220,"timestamp":"2017-07-15T08:13:55"},{"stationid":100,"customerid":210,"timestamp":"2017-07-15T08:14:03"}]}}
```

**Comment by artembilan** [comment]
Just for the info what I see so far.

The JSON splitter indeed returns `LinkedHashMap` by default.
But when I have test like:
```
@SpringBootTest(
			{
					"splitter.expression=#jsonPath(payload,'$.station.readings')",
					"spring.cloud.stream.bindings.output.contentType=application/json"
			})
```
I get the proper JSON in the `output` channel in the test.

Will check that from the SCDF perspective today...

**Comment by sabbyanandan** [comment]
cc:/ @rseroter

**Comment by artembilan** [comment]
With the SCDF I have an error:
```
Caused by: java.lang.IllegalArgumentException: payload must not be null
	at org.springframework.util.Assert.notNull(Assert.java:134) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.integration.support.MutableMessage.<init>(MutableMessage.java:57) ~[spring-integration-core-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.springframework.integration.support.MutableMessage.<init>(MutableMessage.java:53) ~[spring-integration-core-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.springframework.integration.support.MutableMessageBuilder.withPayload(MutableMessageBuilder.java:86) ~[spring-integration-core-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.springframework.integration.support.MutableMessageBuilderFactory.withPayload(MutableMessageBuilderFactory.java:35) ~[spring-integration-core-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.springframework.integration.support.MutableMessageBuilderFactory.withPayload(MutableMessageBuilderFactory.java:26) ~[spring-integration-core-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.springframework.cloud.stream.binding.MessageConverterConfigurer$ContentTypeConvertingInterceptor.preSend(MessageConverterConfigurer.java:250) ~[spring-cloud-stream-1.2.1.RELEASE.jar!/:1.2.1.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel$ChannelInterceptorList.preSend(AbstractMessageChannel.java:538) ~[spring-integration-core-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:415) ~[spring-integration-core-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
```
That's pretty strange because my tests in the `splitter` app are based on the same SCSt version and I see how `MappingJackson2MessageConverter` is selected to convert my `LinkedHashMap` to the JSON String...

**Comment by mbogoevici** [comment]
This happens when an unexpected header is present in the message (`MappingJackson2MessageConverter` returns null when that happens). Should be addressed by https://github.com/spring-cloud/spring-cloud-stream/issues/993.

**Comment by artembilan** [comment]
I think the problem that we have a `contentType=text/plain;charset=UTF-8` which is the result of the `http post` above. When I added `--contentType application/json`. The `splitter` starts to emit data properly:
```
2017-07-10 13:36:48.391 DEBUG 8584 --- [ foo.http.foo-1] o.s.integration.channel.DirectChannel    : postSend (sent=true) on channel 'output', message: GenericMessage [payload={"stationid":100,"customerid":210,"timestamp":"2017-07-15T08:14:03"}, headers={amqp_receivedDeliveryMode=PERSISTENT, content-length=233, http_requestMethod=POST, sequenceNumber=3, amqp_receivedExchange=foo.http, amqp_deliveryTag=2, sequenceSize=3, amqp_consumerQueue=foo.http.foo, amqp_redelivered=false, accept=[text/plain, application/json, application/*+json, */*], accept-charset=[Big5, Big5-HKSCS, CESU-8, EUC-JP, EUC-KR, GB18030, GB2312, GBK, IBM-Thai, IBM00858, IBM01140, IBM01141, IBM01142, IBM01143, IBM01144, IBM01145, IBM01146, IBM01147, IBM01148, IBM01149, IBM037, IBM1026, IBM1047, IBM273, IBM277, IBM278, IBM280, IBM284, IBM285, IBM290, IBM297, IBM420, IBM424, IBM437, IBM500, IBM775, IBM850, IBM852, IBM855, IBM857, IBM860, IBM861, IBM862, IBM863, IBM864, IBM865, IBM866, IBM868, IBM869, IBM870, IBM871, IBM918, ISO-2022-CN, ISO-2022-JP, ISO-2022-JP-2, ISO-2022-KR, ISO-8859-1, ISO-8859-13, ISO-8859-15, ISO-8859-2, ISO-8859-3, ISO-8859-4, ISO-8859-5, ISO-8859-6, ISO-8859-7, ISO-8859-8, ISO-8859-9, JIS_X0201, JIS_X0212-1990, KOI8-R, KOI8-U, Shift_JIS, TIS-620, US-ASCII, UTF-16, UTF-16BE, UTF-16LE, UTF-32, UTF-32BE, UTF-32LE, UTF-8, windows-1250, windows-1251, windows-1252, windows-1253, windows-1254, windows-1255, windows-1256, windows-1257, windows-1258, windows-31j, x-Big5-HKSCS-2001, x-Big5-Solaris, x-euc-jp-linux, x-EUC-TW, x-eucJP-Open, x-IBM1006, x-IBM1025, x-IBM1046, x-IBM1097, x-IBM1098, x-IBM1112, x-IBM1122, x-IBM1123, x-IBM1124, x-IBM1166, x-IBM1364, x-IBM1381, x-IBM1383, x-IBM300, x-IBM33722, x-IBM737, x-IBM833, x-IBM834, x-IBM856, x-IBM874, x-IBM875, x-IBM921, x-IBM922, x-IBM930, x-IBM933, x-IBM935, x-IBM937, x-IBM939, x-IBM942, x-IBM942C, x-IBM943, x-IBM943C, x-IBM948, x-IBM949, x-IBM949C, x-IBM950, x-IBM964, x-IBM970, x-ISCII91, x-ISO-2022-CN-CNS, x-ISO-2022-CN-GB, x-iso-8859-11, x-JIS0208, x-JISAutoDetect, x-Johab, x-MacArabic, x-MacCentralEurope, x-MacCroatian, x-MacCyrillic, x-MacDingbat, x-MacGreek, x-MacHebrew, x-MacIceland, x-MacRoman, x-MacRomania, x-MacSymbol, x-MacThai, x-MacTurkish, x-MacUkraine, x-MS932_0213, x-MS950-HKSCS, x-MS950-HKSCS-XP, x-mswin-936, x-PCK, x-SJIS_0213, x-UTF-16LE-BOM, X-UTF-32BE-BOM, X-UTF-32LE-BOM, x-windows-50220, x-windows-50221, x-windows-874, x-windows-949, x-windows-950, x-windows-iso2022jp], authorization=Basic Om51bGw=, amqp_receivedRoutingKey=foo.http, host=localhost:9000, http_requestUrl=http://localhost:9000/, connection=Keep-Alive, correlationId=93c12d64-4b2c-1ffb-621d-3608eb9de5b8, id=aae7d43d-a1df-d504-a570-5f240309db45, amqp_consumerTag=amq.ctag-FydKmMlVjhxaGvf-ozf8VA, contentType=application/json;charset=UTF-8, accept-encoding=gzip,deflate, user-agent=Apache-HttpClient/4.5.3 (Java/1.8.0_131), timestamp=1499708208389}]
```

**Comment by mbogoevici** [comment]
Yes, because `MappingJackson2MessageConverter` freaks out on the `text/plain` contentType in the header and returns null .... see https://github.com/spring-projects/spring-framework/blob/master/spring-messaging/src/main/java/org/springframework/messaging/converter/AbstractMessageConverter.java#L183. It's not a solution but explains the awkward behaviour (and why Gary's fix solves it).

**Comment by artembilan** [comment]
Now I have this in logs for `field-value-counter`:
```
2017-07-10 13:48:05.130 DEBUG 8652 --- [plit-JSON.bar-1] o.s.integration.channel.DirectChannel    : preSend on channel 'input', message: GenericMessage [payload={"stationid":100,"customerid":210,"timestamp":"2017-07-15T08:14:03"}, headers={amqp_receivedDeliveryMode=PERSISTENT, content-length=233, http_requestMethod=POST, sequenceNumber=3, amqp_receivedExchange=foo.split-JSON, amqp_deliveryTag=3, sequenceSize=3, amqp_consumerQueue=foo.split-JSON.bar, amqp_redelivered=false, accept=[text/plain, application/json, application/*+json, */*], accept-charset=[Big5, Big5-HKSCS, CESU-8, EUC-JP, EUC-KR, GB18030, GB2312, GBK, IBM-Thai, IBM00858, IBM01140, IBM01141, IBM01142, IBM01143, IBM01144, IBM01145, IBM01146, IBM01147, IBM01148, IBM01149, IBM037, IBM1026, IBM1047, IBM273, IBM277, IBM278, IBM280, IBM284, IBM285, IBM290, IBM297, IBM420, IBM424, IBM437, IBM500, IBM775, IBM850, IBM852, IBM855, IBM857, IBM860, IBM861, IBM862, IBM863, IBM864, IBM865, IBM866, IBM868, IBM869, IBM870, IBM871, IBM918, ISO-2022-CN, ISO-2022-JP, ISO-2022-JP-2, ISO-2022-KR, ISO-8859-1, ISO-8859-13, ISO-8859-15, ISO-8859-2, ISO-8859-3, ISO-8859-4, ISO-8859-5, ISO-8859-6, ISO-8859-7, ISO-8859-8, ISO-8859-9, JIS_X0201, JIS_X0212-1990, KOI8-R, KOI8-U, Shift_JIS, TIS-620, US-ASCII, UTF-16, UTF-16BE, UTF-16LE, UTF-32, UTF-32BE, UTF-32LE, UTF-8, windows-1250, windows-1251, windows-1252, windows-1253, windows-1254, windows-1255, windows-1256, windows-1257, windows-1258, windows-31j, x-Big5-HKSCS-2001, x-Big5-Solaris, x-euc-jp-linux, x-EUC-TW, x-eucJP-Open, x-IBM1006, x-IBM1025, x-IBM1046, x-IBM1097, x-IBM1098, x-IBM1112, x-IBM1122, x-IBM1123, x-IBM1124, x-IBM1166, x-IBM1364, x-IBM1381, x-IBM1383, x-IBM300, x-IBM33722, x-IBM737, x-IBM833, x-IBM834, x-IBM856, x-IBM874, x-IBM875, x-IBM921, x-IBM922, x-IBM930, x-IBM933, x-IBM935, x-IBM937, x-IBM939, x-IBM942, x-IBM942C, x-IBM943, x-IBM943C, x-IBM948, x-IBM949, x-IBM949C, x-IBM950, x-IBM964, x-IBM970, x-ISCII91, x-ISO-2022-CN-CNS, x-ISO-2022-CN-GB, x-iso-8859-11, x-JIS0208, x-JISAutoDetect, x-Johab, x-MacArabic, x-MacCentralEurope, x-MacCroatian, x-MacCyrillic, x-MacDingbat, x-MacGreek, x-MacHebrew, x-MacIceland, x-MacRoman, x-MacRomania, x-MacSymbol, x-MacThai, x-MacTurkish, x-MacUkraine, x-MS932_0213, x-MS950-HKSCS, x-MS950-HKSCS-XP, x-mswin-936, x-PCK, x-SJIS_0213, x-UTF-16LE-BOM, X-UTF-32BE-BOM, X-UTF-32LE-BOM, x-windows-50220, x-windows-50221, x-windows-874, x-windows-949, x-windows-950, x-windows-iso2022jp], authorization=Basic Om51bGw=, amqp_receivedRoutingKey=foo.split-JSON, host=localhost:9000, http_requestUrl=http://localhost:9000/, connection=Keep-Alive, correlationId=a664ddd5-e387-54c8-06c5-77cea3f4da47, id=aa16ff39-64cd-6381-ae57-783bc42b7d9e, amqp_consumerTag=amq.ctag-mODaZzcMRq5ahNkYG2T6nQ, contentType=application/json;charset=UTF-8, accept-encoding=gzip,deflate, user-agent=Apache-HttpClient/4.5.3 (Java/1.8.0_131), timestamp=1499708885130}]
2017-07-10 13:48:05.130 DEBUG 8652 --- [plit-JSON.bar-1] o.s.i.handler.ServiceActivatingHandler   : ServiceActivator for [org.springframework.integration.handler.MethodInvokingMessageProcessor@52bff280] (org.springframework.cloud.stream.app.field.value.counter.sink.FieldValueCounterSinkConfiguration.process.serviceActivator.handler) received message: GenericMessage [payload={"stationid":100,"customerid":210,"timestamp":"2017-07-15T08:14:03"}, headers={amqp_receivedDeliveryMode=PERSISTENT, content-length=233, http_requestMethod=POST, sequenceNumber=3, amqp_receivedExchange=foo.split-JSON, amqp_deliveryTag=3, sequenceSize=3, amqp_consumerQueue=foo.split-JSON.bar, amqp_redelivered=false, accept=[text/plain, application/json, application/*+json, */*], accept-charset=[Big5, Big5-HKSCS, CESU-8, EUC-JP, EUC-KR, GB18030, GB2312, GBK, IBM-Thai, IBM00858, IBM01140, IBM01141, IBM01142, IBM01143, IBM01144, IBM01145, IBM01146, IBM01147, IBM01148, IBM01149, IBM037, IBM1026, IBM1047, IBM273, IBM277, IBM278, IBM280, IBM284, IBM285, IBM290, IBM297, IBM420, IBM424, IBM437, IBM500, IBM775, IBM850, IBM852, IBM855, IBM857, IBM860, IBM861, IBM862, IBM863, IBM864, IBM865, IBM866, IBM868, IBM869, IBM870, IBM871, IBM918, ISO-2022-CN, ISO-2022-JP, ISO-2022-JP-2, ISO-2022-KR, ISO-8859-1, ISO-8859-13, ISO-8859-15, ISO-8859-2, ISO-8859-3, ISO-8859-4, ISO-8859-5, ISO-8859-6, ISO-8859-7, ISO-8859-8, ISO-8859-9, JIS_X0201, JIS_X0212-1990, KOI8-R, KOI8-U, Shift_JIS, TIS-620, US-ASCII, UTF-16, UTF-16BE, UTF-16LE, UTF-32, UTF-32BE, UTF-32LE, UTF-8, windows-1250, windows-1251, windows-1252, windows-1253, windows-1254, windows-1255, windows-1256, windows-1257, windows-1258, windows-31j, x-Big5-HKSCS-2001, x-Big5-Solaris, x-euc-jp-linux, x-EUC-TW, x-eucJP-Open, x-IBM1006, x-IBM1025, x-IBM1046, x-IBM1097, x-IBM1098, x-IBM1112, x-IBM1122, x-IBM1123, x-IBM1124, x-IBM1166, x-IBM1364, x-IBM1381, x-IBM1383, x-IBM300, x-IBM33722, x-IBM737, x-IBM833, x-IBM834, x-IBM856, x-IBM874, x-IBM875, x-IBM921, x-IBM922, x-IBM930, x-IBM933, x-IBM935, x-IBM937, x-IBM939, x-IBM942, x-IBM942C, x-IBM943, x-IBM943C, x-IBM948, x-IBM949, x-IBM949C, x-IBM950, x-IBM964, x-IBM970, x-ISCII91, x-ISO-2022-CN-CNS, x-ISO-2022-CN-GB, x-iso-8859-11, x-JIS0208, x-JISAutoDetect, x-Johab, x-MacArabic, x-MacCentralEurope, x-MacCroatian, x-MacCyrillic, x-MacDingbat, x-MacGreek, x-MacHebrew, x-MacIceland, x-MacRoman, x-MacRomania, x-MacSymbol, x-MacThai, x-MacTurkish, x-MacUkraine, x-MS932_0213, x-MS950-HKSCS, x-MS950-HKSCS-XP, x-mswin-936, x-PCK, x-SJIS_0213, x-UTF-16LE-BOM, X-UTF-32BE-BOM, X-UTF-32LE-BOM, x-windows-50220, x-windows-50221, x-windows-874, x-windows-949, x-windows-950, x-windows-iso2022jp], authorization=Basic Om51bGw=, amqp_receivedRoutingKey=foo.split-JSON, host=localhost:9000, http_requestUrl=http://localhost:9000/, connection=Keep-Alive, correlationId=a664ddd5-e387-54c8-06c5-77cea3f4da47, id=aa16ff39-64cd-6381-ae57-783bc42b7d9e, amqp_consumerTag=amq.ctag-mODaZzcMRq5ahNkYG2T6nQ, contentType=application/json;charset=UTF-8, accept-encoding=gzip,deflate, user-agent=Apache-HttpClient/4.5.3 (Java/1.8.0_131), timestamp=1499708885130}]
2017-07-10 13:48:05.131 DEBUG 8652 --- [plit-JSON.bar-1] o.s.i.handler.ServiceActivatingHandler   : handler 'ServiceActivator for [org.springframework.integration.handler.MethodInvokingMessageProcessor@52bff280] (org.springframework.cloud.stream.app.field.value.counter.sink.FieldValueCounterSinkConfiguration.process.serviceActivator.handler)' produced no reply for request Message: GenericMessage [payload={"stationid":100,"customerid":210,"timestamp":"2017-07-15T08:14:03"}, headers={amqp_receivedDeliveryMode=PERSISTENT, content-length=233, http_requestMethod=POST, sequenceNumber=3, amqp_receivedExchange=foo.split-JSON, amqp_deliveryTag=3, sequenceSize=3, amqp_consumerQueue=foo.split-JSON.bar, amqp_redelivered=false, accept=[text/plain, application/json, application/*+json, */*], accept-charset=[Big5, Big5-HKSCS, CESU-8, EUC-JP, EUC-KR, GB18030, GB2312, GBK, IBM-Thai, IBM00858, IBM01140, IBM01141, IBM01142, IBM01143, IBM01144, IBM01145, IBM01146, IBM01147, IBM01148, IBM01149, IBM037, IBM1026, IBM1047, IBM273, IBM277, IBM278, IBM280, IBM284, IBM285, IBM290, IBM297, IBM420, IBM424, IBM437, IBM500, IBM775, IBM850, IBM852, IBM855, IBM857, IBM860, IBM861, IBM862, IBM863, IBM864, IBM865, IBM866, IBM868, IBM869, IBM870, IBM871, IBM918, ISO-2022-CN, ISO-2022-JP, ISO-2022-JP-2, ISO-2022-KR, ISO-8859-1, ISO-8859-13, ISO-8859-15, ISO-8859-2, ISO-8859-3, ISO-8859-4, ISO-8859-5, ISO-8859-6, ISO-8859-7, ISO-8859-8, ISO-8859-9, JIS_X0201, JIS_X0212-1990, KOI8-R, KOI8-U, Shift_JIS, TIS-620, US-ASCII, UTF-16, UTF-16BE, UTF-16LE, UTF-32, UTF-32BE, UTF-32LE, UTF-8, windows-1250, windows-1251, windows-1252, windows-1253, windows-1254, windows-1255, windows-1256, windows-1257, windows-1258, windows-31j, x-Big5-HKSCS-2001, x-Big5-Solaris, x-euc-jp-linux, x-EUC-TW, x-eucJP-Open, x-IBM1006, x-IBM1025, x-IBM1046, x-IBM1097, x-IBM1098, x-IBM1112, x-IBM1122, x-IBM1123, x-IBM1124, x-IBM1166, x-IBM1364, x-IBM1381, x-IBM1383, x-IBM300, x-IBM33722, x-IBM737, x-IBM833, x-IBM834, x-IBM856, x-IBM874, x-IBM875, x-IBM921, x-IBM922, x-IBM930, x-IBM933, x-IBM935, x-IBM937, x-IBM939, x-IBM942, x-IBM942C, x-IBM943, x-IBM943C, x-IBM948, x-IBM949, x-IBM949C, x-IBM950, x-IBM964, x-IBM970, x-ISCII91, x-ISO-2022-CN-CNS, x-ISO-2022-CN-GB, x-iso-8859-11, x-JIS0208, x-JISAutoDetect, x-Johab, x-MacArabic, x-MacCentralEurope, x-MacCroatian, x-MacCyrillic, x-MacDingbat, x-MacGreek, x-MacHebrew, x-MacIceland, x-MacRoman, x-MacRomania, x-MacSymbol, x-MacThai, x-MacTurkish, x-MacUkraine, x-MS932_0213, x-MS950-HKSCS, x-MS950-HKSCS-XP, x-mswin-936, x-PCK, x-SJIS_0213, x-UTF-16LE-BOM, X-UTF-32BE-BOM, X-UTF-32LE-BOM, x-windows-50220, x-windows-50221, x-windows-874, x-windows-949, x-windows-950, x-windows-iso2022jp], authorization=Basic Om51bGw=, amqp_receivedRoutingKey=foo.split-JSON, host=localhost:9000, http_requestUrl=http://localhost:9000/, connection=Keep-Alive, correlationId=a664ddd5-e387-54c8-06c5-77cea3f4da47, id=aa16ff39-64cd-6381-ae57-783bc42b7d9e, amqp_consumerTag=amq.ctag-mODaZzcMRq5ahNkYG2T6nQ, contentType=application/json;charset=UTF-8, accept-encoding=gzip,deflate, user-agent=Apache-HttpClient/4.5.3 (Java/1.8.0_131), timestamp=1499708885130}]
2017-07-10 13:48:05.131 DEBUG 8652 --- [plit-JSON.bar-1] o.s.integration.channel.DirectChannel    : postSend (sent=true) on channel 'input', message: GenericMessage [payload={"stationid":100,"customerid":210,"timestamp":"2017-07-15T08:14:03"}, headers={amqp_receivedDeliveryMode=PERSISTENT, content-length=233, http_requestMethod=POST, sequenceNumber=3, amqp_receivedExchange=foo.split-JSON, amqp_deliveryTag=3, sequenceSize=3, amqp_consumerQueue=foo.split-JSON.bar, amqp_redelivered=false, accept=[text/plain, application/json, application/*+json, */*], accept-charset=[Big5, Big5-HKSCS, CESU-8, EUC-JP, EUC-KR, GB18030, GB2312, GBK, IBM-Thai, IBM00858, IBM01140, IBM01141, IBM01142, IBM01143, IBM01144, IBM01145, IBM01146, IBM01147, IBM01148, IBM01149, IBM037, IBM1026, IBM1047, IBM273, IBM277, IBM278, IBM280, IBM284, IBM285, IBM290, IBM297, IBM420, IBM424, IBM437, IBM500, IBM775, IBM850, IBM852, IBM855, IBM857, IBM860, IBM861, IBM862, IBM863, IBM864, IBM865, IBM866, IBM868, IBM869, IBM870, IBM871, IBM918, ISO-2022-CN, ISO-2022-JP, ISO-2022-JP-2, ISO-2022-KR, ISO-8859-1, ISO-8859-13, ISO-8859-15, ISO-8859-2, ISO-8859-3, ISO-8859-4, ISO-8859-5, ISO-8859-6, ISO-8859-7, ISO-8859-8, ISO-8859-9, JIS_X0201, JIS_X0212-1990, KOI8-R, KOI8-U, Shift_JIS, TIS-620, US-ASCII, UTF-16, UTF-16BE, UTF-16LE, UTF-32, UTF-32BE, UTF-32LE, UTF-8, windows-1250, windows-1251, windows-1252, windows-1253, windows-1254, windows-1255, windows-1256, windows-1257, windows-1258, windows-31j, x-Big5-HKSCS-2001, x-Big5-Solaris, x-euc-jp-linux, x-EUC-TW, x-eucJP-Open, x-IBM1006, x-IBM1025, x-IBM1046, x-IBM1097, x-IBM1098, x-IBM1112, x-IBM1122, x-IBM1123, x-IBM1124, x-IBM1166, x-IBM1364, x-IBM1381, x-IBM1383, x-IBM300, x-IBM33722, x-IBM737, x-IBM833, x-IBM834, x-IBM856, x-IBM874, x-IBM875, x-IBM921, x-IBM922, x-IBM930, x-IBM933, x-IBM935, x-IBM937, x-IBM939, x-IBM942, x-IBM942C, x-IBM943, x-IBM943C, x-IBM948, x-IBM949, x-IBM949C, x-IBM950, x-IBM964, x-IBM970, x-ISCII91, x-ISO-2022-CN-CNS, x-ISO-2022-CN-GB, x-iso-8859-11, x-JIS0208, x-JISAutoDetect, x-Johab, x-MacArabic, x-MacCentralEurope, x-MacCroatian, x-MacCyrillic, x-MacDingbat, x-MacGreek, x-MacHebrew, x-MacIceland, x-MacRoman, x-MacRomania, x-MacSymbol, x-MacThai, x-MacTurkish, x-MacUkraine, x-MS932_0213, x-MS950-HKSCS, x-MS950-HKSCS-XP, x-mswin-936, x-PCK, x-SJIS_0213, x-UTF-16LE-BOM, X-UTF-32BE-BOM, X-UTF-32LE-BOM, x-windows-50220, x-windows-50221, x-windows-874, x-windows-949, x-windows-950, x-windows-iso2022jp], authorization=Basic Om51bGw=, amqp_receivedRoutingKey=foo.split-JSON, host=localhost:9000, http_requestUrl=http://localhost:9000/, connection=Keep-Alive, correlationId=a664ddd5-e387-54c8-06c5-77cea3f4da47, id=aa16ff39-64cd-6381-ae57-783bc42b7d9e, amqp_consumerTag=amq.ctag-mODaZzcMRq5ahNkYG2T6nQ, contentType=application/json;charset=UTF-8, accept-encoding=gzip,deflate, user-agent=Apache-HttpClient/4.5.3 (Java/1.8.0_131), timestamp=1499708885130}]
```
So, looks like it confirms that it works.

@sabbyanandan ,

how is that for your scenario with the `--contentType application/json` for the `http post`?

**Comment by artembilan** [comment]
Well, I'd say that it now really works well:
```
127.0.0.1:6379> zrange fieldvaluecounters.salsa 0 -1
1) "101"
2) "100"
```


So, there is no problem with `splitter`, the problem on the SCSt has been fixed (thanks to @mbogoevici  and @garyrussell ). Now we have to go to the `field-value-counter` and add support for the incoming `Map` payload. Because the test against `Map` ends up with the `NPE`. And the funny thing that we just ignore nonexistent property:
```
private void processPojo(String counterName, Object payload) {
	BeanWrapper beanWrapper = new BeanWrapperImpl(payload);
	if (beanWrapper.isReadableProperty(fvcSinkProperties.getFieldName())) {
		Object value = beanWrapper.getPropertyValue(fvcSinkProperties.getFieldName());
		processValue(counterName, value);
	}
}
```

😢

**Comment by sabbyanandan** [comment]
@artembilan: I tried the same streams with `--contentType application/json` in the post. I don't see the error when the apps themselves are marked to expect the payload as `application/json`, but at the same time, I don't see it working either. 

```
stream create foo --definition "http --port=8086 | split-JSON: splitter --expression=#jsonPath(payload,'$.station.readings') --spring.cloud.stream.bindings.output.contentType='application/json' | log"
stream create bar --definition ":foo.split-JSON > field-value-counter --name=salsa --fieldName=stationid --spring.cloud.stream.bindings.input.contentType='application/json'"
```

> dataflow:>http post --target http://localhost:8086 --data {"station":{"readings":[{"stationid":100,"customerid":200,"timestamp":"2017-07-15T08:09:10"},{"stationid":101,"customerid":220,"timestamp":"2017-07-15T08:13:55"},{"stationid":100,"customerid":210,"timestamp":"2017-07-15T08:14:03"}]}} --contentType application/json

**Comment by sabbyanandan** [comment]
I take it back. I'm able to see the results with the previous stream definition + post combination. 

```
dataflow:>field-value-counter display salsa
Displaying values for field value counter 'salsa'
╔═════╤═════╗
║Value│Count║
╠═════╪═════╣
║100  │    2║
║101  │    1║
╚═════╧═════╝
```

@rseroter: It'd be great if you can try it on your end as well. You don't need to plug `--spring.cloud.stream.bindings.output.contentType` and `--spring.cloud.stream.bindings.input.contentType` on the DSL (it won't hurt even if it is there), but please make sure to pass `--contentType application/json` in the post. Once after you confirm, we can close the issue.

@artembilan: As for the FVC, I agree it'd be beneficial to support `Map` and handle the error condition more gracefully. We can move the scope to FVC repo.

**Comment by rseroter** [comment]
Sabby's last version worked for me. I was setting the --outputType property on the splitter, and not the stream binding contentType.

**Comment by rseroter** [comment]
Without the contentType, my FVC still throws an exception.

**Comment by sabbyanandan** [comment]
Thanks for the feedback, @rseroter. 

I see the same behavior. Too many attempts with different combinations made it hard to pin which combination worked. Though supplying `contentType` in the http-post should have automatically propagated the desired negotiation strategy all the way through, it does not seem to be working in this case. We will investigate it as part of the overall feature review. For the time being, please continue to supply `--spring.cloud.stream.bindings.output.contentType` and `--spring.cloud.stream.bindings.input.contentType`.

Another data point to make progress on the end-to-end test coverage of this feature via: spring-cloud/spring-cloud-stream#992.

**Comment by viniciusccarvalho** [comment]
Depending on which version of http-source you are using, you will need to set `http.mapped-request-headers` in order to propagate the `contentType`

It never hurts saying this once again : We need better contracts between our apps, otherwise this is the default behavior we see for a lot of our users. At a given point I hope someone agrees on this and we can design stronger contracts between our apps
